  version: '3'

  volumes:
    postgres_data_vol:
      external: false
    python_requirements_vol:
      external: false

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      stdin_open: true
      volumes:
        - postgres_data_vol:/var/lib/postgresql/data/
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:2021
      restart: unless-stopped
      ports:
        - "2021:2021"
      depends_on:
        - db
      stdin_open: true
      volumes:
        - ./:/code:cached
        - python_requirements_vol:/usr/local/lib/python3.9
    requirements:
      build: .
      tty: true
      command:
        - /bin/bash
        - -c
        - pip3 install -r requirements.txt &&
          (python3 -m compileall /usr/local/lib/python3.9 || true) &&
          rm -Rf /python3.9/* &&
          cp -Rf -p /usr/local/lib/python3.9 /
      restart: 'no'
      environment:
        PYTHONUNBUFFERED: 0 # This when set to 0 will allow print statements to be visible in the Docker logs
        DJANGO_SETTINGS_MODULE: api.base.settings
      volumes:
        - ./:/code:cached
        - python_requirements_vol:/python3.9
