# Generated by Django 3.1.1 on 2022-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='registration_response_key',
            field=models.CharField(blank=True, default='', help_text='This is legacy for bulk uploads', max_length=5000, null=True),
        ),
    ]
