# Generated by Django 3.1.1 on 2021-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_spamdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamdata',
            name='guidid',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='spamdata',
            unique_together=set(),
        ),
    ]
