# Generated by Django 3.1.1 on 2022-11-22 14:25

from django.db import migrations
import web.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_block_registration_response_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=web.fields.EncryptedTextField(blank=True, max_length=500, null=True),
        ),
    ]
