# Generated by Django 3.1.1 on 2021-08-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210805_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spamdata',
            old_name='guidid',
            new_name='guid',
        ),
    ]
