# Generated by Django 3.1.1 on 2021-08-12 19:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210805_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamRegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SpamData',
            new_name='SpamUserData',
        ),
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, max_length=5, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.spamregistrationdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spamregistrationdata',
            name='spam_reports',
            field=models.ManyToManyField(through='web.SpamReport', to=settings.AUTH_USER_MODEL),
        ),
    ]
