# Generated by Django 3.1.1 on 2021-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_auto_20210621_1516"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="csv_uploads",
        ),
        migrations.AlterField(
            model_name="schema",
            name="csv_uploads",
            field=models.FileField(null=True, upload_to="csv_uploads/"),
        ),
    ]
