# Generated by Django 3.1.1 on 2021-08-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpamRegistrationData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("raw_json", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpamUserData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=500, null=True)),
                ("social", models.JSONField(blank=True, null=True)),
                ("education", models.JSONField(blank=True, null=True)),
                ("employment", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpamReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spam_scan.spamregistrationdata",
                    ),
                ),
            ],
        ),
    ]
