# Generated by Django 3.1.1 on 2021-08-29 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spam_scan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spamreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="spamregistrationdata",
            name="spam_reports",
            field=models.ManyToManyField(
                through="spam_scan.SpamReport", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
