# Generated by Django 3.1.1 on 2021-10-21 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spam_scan', '0002_auto_20210829_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSpamReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_spam_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spam_scan.spamuserdata')),
            ],
        ),
    ]
